packages:
  - .

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - cpu-features
  - electron-winstaller
  - esbuild
  - protobufjs
  - ssh2
  - unrs-resolver

onlyBuiltDependencies:
  - electron
