name: Security (cron)
on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  rust-audit:
    runs-on: ubuntu-latest
    # Keep version in sync with rust-toolchain.toml
    container: rust:1.84.1
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Check Rust dependencies
        run: |
          cargo install cargo-audit
          cargo audit
